#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — local development credentials for track-record.
#
# Fills the values wrangler needs in .dev.vars, then puts the schema in the
# local database. Safe to re-run: every value already present is offered back
# as the default, and the schema step is skipped when the tables exist.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE=".dev.vars"

# .dev.vars and the migration glob are repo-relative, so anchor to the repo
# root no matter where the wizard is invoked from.
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

# The file is written with quoted values; strip the quotes when we need to
# show a value back to the human or build a URL out of it.
unquote() { local v="$1"; v="${v%\"}"; v="${v#\"}"; printf '%s' "$v"; }

banner "track-record — local development credentials"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Local values"
say "No browser needed. These are the values that don't come from a vendor."
say ""
ask DEV_PORT "Port Vite is serving on [5173]:"
DEV_PORT=$(unquote "${DEV_PORT:-5173}")
[[ -z "$DEV_PORT" ]] && DEV_PORT=5173
REDIRECT_URI="http://localhost:${DEV_PORT}/api/auth/callback/google"

step "Your Google account — the only address allowed to sign in (docs/08 §2)."
ask ALLOWED_SIGNUP_EMAILS "Email address:"
ALLOWED_SIGNUP_EMAILS=$(unquote "$ALLOWED_SIGNUP_EMAILS")

# Kept across re-runs on purpose: regenerating it invalidates every session.
BETTER_AUTH_SECRET=$(_existing BETTER_AUTH_SECRET || true)
if [[ -z "$BETTER_AUTH_SECRET" ]]; then
  BETTER_AUTH_SECRET="\"$(openssl rand -base64 32)\""
  note "generated a new BETTER_AUTH_SECRET"
else
  note "keeping the existing BETTER_AUTH_SECRET — regenerating it would sign you out"
fi

# localhost in the host sends src/server/db/client.ts through the Neon HTTP
# proxy on :4444, which is what docker-compose.yml puts in front of Postgres.
write_env DATABASE_URL "\"postgresql://postgres:postgres@localhost:5432/track_record_test?sslmode=disable\""
write_env ANTHROPIC_MODEL "\"claude-opus-5\""
write_env BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET"
# The Vite origin, not the Worker's — Vite proxies /api to :8787, so the OAuth
# round trip stays on the origin serving the live SPA.
write_env BETTER_AUTH_URL "\"http://localhost:${DEV_PORT}\""
write_env ALLOWED_SIGNUP_EMAILS "\"${ALLOWED_SIGNUP_EMAILS}\""
pause "Done. Press Enter for the Google Cloud stages."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud — a project to hold the OAuth client"
say "Skip to the next stage if you already have a project for this."
open_url "https://console.cloud.google.com/projectcreate"
step "Project name: track-record-dev (anything works — it is a label)."
step "Leave Location as No organisation unless you have one."
step "Click Create, then wait for the notification and select the project."
pause "Project created and selected?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Google Auth Platform — consent screen"
say "Google renamed this from 'OAuth consent screen'. It lives under"
say "Google Auth Platform now, and must exist before a client can be created."
open_url "https://console.cloud.google.com/auth/overview"
step "Click Get started."
step "App name: Track Record. User support email: your own address."
step "Audience: External. (Internal needs a Workspace organisation.)"
step "Contact information: your own address again."
step "Agree to the User Data Policy, then Create."
pause "Consent screen configured?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Google Auth Platform — audience"
open_url "https://console.cloud.google.com/auth/audience"
step "Under Test users, click Add users and add: ${ALLOWED_SIGNUP_EMAILS}"
step "Save."
say ""
warn "In Testing status, a consent expires 7 days after you grant it."
note "You would have to re-consent every week. This app asks for openid, email"
note "and profile only — all non-sensitive — so Publish app moves it to"
note "Production with no verification review, and the expiry goes away."
say ""
step "Recommended: click Publish app, and confirm."
pause "Test user added (and published, if you chose to)?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Google Auth Platform — OAuth client"
say "This is the value the app actually needs."
open_url "https://console.cloud.google.com/auth/clients/create"
step "Application type: Web application."
step "Name: track-record local dev."
step "Authorised JavaScript origins → Add URI:  http://localhost:${DEV_PORT}"
step "Authorised redirect URIs → Add URI:"
say  "      ${REDIRECT_URI}"
note "That URI must match exactly — scheme, port and path. A mismatch is the"
note "redirect_uri_mismatch error you would otherwise hit at sign-in."
say ""
warn "Do not add any scope beyond openid, email and profile."
note "Never a Gmail, Drive or Calendar scope. Release blocker, not a hardening"
note "task — CLAUDE.md and docs/08-auth-and-permissions.md."
say ""
step "Click Create. A dialog shows the ID and the secret."
warn "Copy the secret now — the dialog never shows it again."
ask GOOGLE_CLIENT_ID "Paste the Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Paste the Client secret (hidden):"
write_env GOOGLE_CLIENT_ID "\"$(unquote "$GOOGLE_CLIENT_ID")\""
write_env GOOGLE_CLIENT_SECRET "\"$(unquote "$GOOGLE_CLIENT_SECRET")\""

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Anthropic — API key for the import pipeline"
say "Fact extraction calls claude-opus-5. Without this key, sign-in and the"
say "renders work, but an import fails at the extraction step."
open_url "https://console.anthropic.com/settings/keys"
step "Create a Workspace for this project if you have not — not Default."
step "Give that workspace its own spend limit (docs/13 §5)."
step "Create Key, scoped to that workspace, then copy it."
warn "Scope the key to that workspace, not the account."
note "A workspace key caps the blast radius if it leaks. An account key does"
note "not, and this repo is public."
ask_secret ANTHROPIC_API_KEY "Paste the API key (hidden):"
write_env ANTHROPIC_API_KEY "\"$(unquote "$ANTHROPIC_API_KEY")\""

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Database schema"
say "npm run db:migrate does not work against the local stack — drizzle-kit"
say "connects over WebSocket and the proxy in docker-compose.yml is HTTP only."
say "The committed migration SQL goes in through psql instead."
say ""

PSQL="docker compose exec -T postgres psql -v ON_ERROR_STOP=1 -U postgres -d track_record_test"
if ! docker compose ps postgres >/dev/null 2>&1; then
  warn "Postgres is not running — start it with: npm run db:up"
  SKIPPED+=("apply migrations (run npm run db:up, then re-run this wizard)")
elif $PSQL -c '\d users' >/dev/null 2>&1; then
  note "the schema is already applied — nothing to do"
else
  step "Applying src/server/db/migrations/*.sql"
  if confirm "Apply the migrations now?"; then
    for f in src/server/db/migrations/*.sql; do
      if $PSQL < "$f" >/dev/null 2>&1; then
        note "  applied $(basename "$f")"
      else
        warn "  failed on $(basename "$f")"
        SKIPPED+=("migration $(basename "$f") — apply it by hand")
      fi
    done
  else
    SKIPPED+=("apply migrations")
  fi
fi

say ""
note "npm test drops and recreates the public schema on every run — do not run"
note "it in the middle of a manual walkthrough or it will wipe your account."

finish

printf '  %sNext:%s\n' "$BOLD" "$RESET"
printf '    1. Restart the worker so wrangler reads .dev.vars:  npm run dev:worker\n'
printf '    2. Make sure Vite is up on :%s:                     npm run dev\n' "$DEV_PORT"
printf '    3. Sign in, import a document, accept the facts, export the resume.\n\n'
